### ISSUE TITLE
Training on GPU

### ISSUE THREAD

**Issue by prabaskrishnan** [Rsheikh-shab/Yolov4-with-Tensorflow#1]
Does it automatically run on GPU if it finds one in the machine where you are training this? Also would it work with multi-gpu machine?

**Comment by Rsheikh-shab** [comment]
@prabaskrishnan yes it will automatically detect GPU if tensorflow-gpu version is installed. Otherwise CPU version will run the inference.  It can also work with multiple GPUs, though I didn't try yet. You may check this to run with multiple GPUs https://jhui.github.io/2017/03/07/TensorFlow-GPU/
